server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    session:
      timeout: 1h					
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@//localhost:1521/XEPDB1}
    hikari:
      username: ${DB_USER:noexit}
      password: ${DB_PASSWORD:noexit}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER:noreply@example.com}
    password: ${MAIL_PASS:dummy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

